const constants = {
  ADD_CARD: "CREATE_A_NEW_CARD",
  MOVE_CARD: "MOVE_A_CARD",
  REMOVE_CARD: "REMOVE_A_CARD",
  ADD_LIST: "CREATE_A_NEW_LIST",
  MOVE_LIST: "MOVE_A_LIST",
  REMOVE_LIST: "REMOVE_A_LIST",
  RENAME_LIST: "RENAME_A_LIST",
};
export default constants;
